services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oficinaliderrefrigeracao-prod
    restart: always
    environment:
      - PORT=80
      - NODE_ENV=production
    networks:
      - traefik_public
      - mysql_shared
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.oficinaliderrefrigeracao-prod.rule=Host(`oficinaliderrefrigeracao.com.br`)"
      - "traefik.http.routers.oficinaliderrefrigeracao-prod.entrypoints=websecure"
      - "traefik.http.routers.oficinaliderrefrigeracao-prod.tls=true"
      - "traefik.http.routers.oficinaliderrefrigeracao-prod.tls.certresolver=le"
      - "traefik.http.routers.oficinaliderrefrigeracao-prod.service=oficinaliderrefrigeracao-prod"
      - "traefik.http.services.oficinaliderrefrigeracao-prod.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
  mysql_shared:
    external: true
