name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Garante que a pasta existe ou clona o projeto se estiver vazio
            if [ ! -d "/var/www/liderRefrigeracao/.git" ]; then
              sudo mkdir -p /var/www/liderRefrigeracao
              sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} /var/www/liderRefrigeracao
              git clone https://github.com/${{ github.repository }}.git /var/www/liderRefrigeracao
            fi

            cd /var/www/liderRefrigeracao
            
            # Puxa as alterações da branch selecionada
            git pull origin ${{ github.ref_name }}
            
            # Cria o arquivo .env no backend
            echo "${{ secrets.ENV_PROD }}" > backend/.env
            
            # Sobe os containers (Build da imagem e deploy)
            docker compose -f docker-compose.prod.yml up -d --build
            
            # Limpa imagens não utilizadas
            docker image prune -f
